import {AbstractError} from "./abstract_error";

export enum OxygenErrorCode {
    GENERAL_ERROR = 10000,

    FATAL_ERROR = 10076,

    RSA_KEY_OPENSSL_VERIFY_ERROR = 10001,

    RSA_KEY_PARSING_FAILED = 10002,
    RSA_KEY_MISSING_ASN1_SEQUENCE = 10003,
    RSA_KEY_MISSING_ASN1_OBJECT = 10004,
    RSA_KEY_MISSING_ASN1_BITSTRING = 10005,
    RSA_KEY_MISSING_ASN1_INTEGER = 10006,
    RSA_KEY_INVALID_LENGTH = 10007,
    RSA_KEY_UNSUPPORTED_ENCRYPTION = 10008,
    RSA_KEY_SIGNATURE_REPRESENTATIVE_OUT_OF_RANGE = 10009,
    RSA_KEY_SIGNATURE_INVALID = 10010,
    RSA_KEY_INVALID_FORMAT = 10011,
    RSA_KEY_SIGNATURE_SIZE_INVALID = 10012,
    RSA_KEY_MODULUS_SIZE_INVALID = 10013,
    RSA_KEY_ENCODED_SIZE_INVALID = 10014,

    ACTION_NOT_FOUND = 10015,
    ACTION_ARGUMENT_NOT_PROVIDED = 10024,

    NONCE_EXPIRED = 10017,
    NONCE_ALREADY_USED = 10018,

    HANDSHAKE_VERIFY_TEST_FAILED = 10022,
    HANDSHAKE_VERIFY_FAILED = 10023,
    HANDSHAKE_LOCAL_KEY_NOT_FOUND = 10042,
    HANDSHAKE_LOCAL_VERIFY_FAILED = 10043,

    PROTOCOL_PUBLIC_KEY_NOT_PROVIDED = 10019,
    PROTOCOL_PUBLIC_KEY_NOT_VALID = 10025,
    PROTOCOL_SIGNATURE_NOT_VALID = 10026,
    PROTOCOL_SIGNATURE_NOT_PROVIDED = 10020,
    PROTOCOL_EXPIRATION_NOT_PROVIDED = 10021,
    PROTOCOL_EXPIRATION_NOT_VALID = 10027,
    PROTOCOL_ACTION_NAME_NOT_PROVIDED = 10030,
    PROTOCOL_ACTION_NAME_NOT_VALID = 10031,
    PROTOCOL_ACTION_PARAMETERS_NOT_PROVIDED = 10032,
    PROTOCOL_ACTION_PARAMETERS_NOT_VALID = 10033,
    PROTOCOL_VERSION_NOT_PROVIDED = 10028,
    PROTOCOL_VERSION_NOT_VALID = 10029,
    PROTOCOL_VERSION_TOO_LOW = 10034,
    PROTOCOL_HANDSHAKE_KEY_NOT_PROVIDED = 10035,
    PROTOCOL_HANDSHAKE_KEY_NOT_VALID = 10036,
    PROTOCOL_HANDSHAKE_SIGNATURE_NOT_PROVIDED = 10037,
    PROTOCOL_HANDSHAKE_SIGNATURE_NOT_VALID = 10038,
    PROTOCOL_BASE_URL_NOT_PROVIDED = 10039,
    PROTOCOL_BASE_URL_NOT_VALID = 10040,
    PROTOCOL_BASE_URL_SLUG_MISMATCHES = 10041,
    PROTOCOL_REQUEST_ID_NOT_PROVIDED = 10044,
    PROTOCOL_REQUEST_ID_NOT_VALID = 10045,
    PROTOCOL_USER_NAME_NOT_PROVIDED = 10049,
    PROTOCOL_USER_NAME_NOT_VALID = 10048,
    PROTOCOL_USER_UID_NOT_PROVIDED = 10050,
    PROTOCOL_USER_UID_NOT_VALID = 10051,
    PROTOCOL_STATE_PARAMETERS_NOT_PROVIDED = 10077,
    PROTOCOL_STATE_PARAMETERS_NOT_VALID = 10078,

    PUBLIC_KEY_MISSING = 10046,

    AUTO_LOGIN_CAN_NOT_FIND_USER = 10047,

    MULTIPART_ENCODING_NOT_SUPPORTED = 10052,

    ARCHIVE_FILE_NOT_FOUND = 10053,
    ARCHIVE_TAR_ZLIB_EXTENSION_NOT_LOADED = 10054,
    ARCHIVE_TAR_DESTINATION_DOES_NOT_EXIST = 10055,
    ARCHIVE_TAR_FILE_EXISTS_AS_DIRECTORY = 10056,
    ARCHIVE_TAR_DIRECTORY_EXISTS_AS_FILE = 10057,
    ARCHIVE_TAR_FILE_IS_WRITE_PROTECTED = 10058,
    ARCHIVE_TAR_DIRECTORY_CAN_NOT_BE_CREATED = 10059,
    ARCHIVE_TAR_UNABLE_TO_OPEN_FILE_FOR_WRITING = 10060,
    ARCHIVE_TAR_FILE_SIZE_MISMATCH = 10061,
    ARCHIVE_TAR_INVALID_BLOCK_SIZE = 10062,
    ARCHIVE_TAR_CHECKSUM_NOT_VALID = 10063,
    ARCHIVE_TAR_FILE_NAME_CONTAINS_DIRECTORY_TRAVERSAL = 10064,

    ARCHIVE_ZIP_EXTENSION_NOT_LOADED = 10065,
    ARCHIVE_ZIP_EXTENSION_ERROR = 10066,

    PROJECT_MANAGER_UNABLE_TO_RETRIEVE_DRUPAL_PROJECT = 10067,
    PROJECT_MANAGER_EXTRACT_FAILED = 10068,
    PROJECT_MANAGER_ARCHIVE_CONTAINS_NO_FILES = 10069,
    PROJECT_MANAGER_ARCHIVE_VERIFY_ERROR = 10070,
    PROJECT_MANAGER_CAN_NOT_FIND_APPROPRIATE_UPDATER = 10071,
    PROJECT_MANAGER_UNABLE_TO_PARSE_PROJECT_INFO = 10072,
    PROJECT_MANAGER_UNABLE_TO_DETERMINE_PROJECT_NAME = 10073,
    PROJECT_MANAGER_PROJECT_ALREADY_INSTALLED = 10074,
    PROJECT_MANAGER_FILE_SYSTEM_NOT_WRITABLE = 10075,
}

export class OxygenError extends AbstractError {
    get class(): string {
        return this.data.class;
    }

    get message(): string {
        return this.data.message;
    }

    get code(): OxygenErrorCode {
        return this.data.code;
    }

    get type(): string|void {
        return this.data.type;
    }

    get file(): string {
        return this.data.file;
    }

    get line(): number {
        return this.data.line;
    }

    get trace(): string {
        return this.data.trace;
    }
}
